### PR TITLE
-fixes for:beans without a name attribute, "resource" attribute property resolving, anonymous beans are inserted only once

### PR DESCRIPTION
**Pull request by mfyuce**
-"resource" attribute property resolving
-beans without a name attribute still to be used with templating: "${" becomes "----" (four times "-") on id and "}" becomes "____" (four times "_") on id
-anonymous beans are inserted only once, no exceptions.

### CODE REVIEW

**Comment by MarkusBernhardt** [comment]
Thanks a lot for your help

**Comment by mfyuce** [comment]
Thanks for the great code.

**Comment by MarkusBernhardt** [comment]
Hi, on my machine the unit tests are not working any more. Will fix them before pushing out a release.

**Comment by MarkusBernhardt** [comment]
Released 1.0.4.
Perhaps you can retest your text replacements.

**Comment by mfyuce** [comment]
Thanks for the release.

Everything seems OK on my side.

**Comment by mfyuce** [comment]
Also thanks for the nice refactorings

**Pull request merged**
